# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-12-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeatureOne', models.BooleanField(verbose_name=b'self')),
                ('FeatureTwo', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=100, verbose_name=b'Main entity name')),
                ('entity_type', models.CharField(max_length=100, verbose_name=b'Main entity type')),
                ('EntityOne', models.ManyToManyField(null=True, related_name='_root_EntityOne_+', to='main.Root')),
                ('EntityTwo', models.ManyToManyField(null=True, related_name='_root_EntityTwo_+', to='main.Root')),
            ],
        ),
    ]
