# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-12-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureone', models.BooleanField(verbose_name=b'self')),
                ('entity_name', models.CharField(max_length=100, verbose_name=b'Main entity name')),
                ('entity_type', models.CharField(max_length=100, verbose_name=b'Main entity type')),
                ('entityone', models.ManyToManyField(related_name='_root_entityone_+', to='main.Root')),
            ],
        ),
    ]
